Repository FC-DEV-FinalProject/FinalProject_team3_FE, pull requests merged in 2024-12, with the labels that each got.

#175 [Feat] 전략 상세 분석&리뷰 api 및 tanstack-query 추가
  app/(dashboard)/_ui/analysis-container/account-content.tsx
  app/(dashboard)/_ui/analysis-container/analysis-chart.stories.tsx
  app/(dashboard)/_ui/analysis-container/analysis-chart.tsx
  app/(dashboard)/_ui/analysis-container/analysis-content.tsx
  app/(dashboard)/_ui/analysis-container/example.ts
  app/(dashboard)/_ui/analysis-container/index.tsx
  app/(dashboard)/_ui/analysis-container/statistics-content.tsx
  app/(dashboard)/_ui/analysis-container/styles.module.scss
  app/(dashboard)/_ui/analysis-container/tabs-width-table.tsx
  app/(dashboard)/_ui/analysis-container/yaxis-options.ts
  app/(dashboard)/_ui/subscriber-item/index.tsx
  app/(dashboard)/_ui/subscriber-item/styles.module.scss
  app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
  app/(dashboard)/strategies/[strategyId]/_api/get-analysis-chart.ts
  app/(dashboard)/strategies/[strategyId]/_api/get-analysis.ts
  app/(dashboard)/strategies/[strategyId]/_api/get-reviews.ts
  app/(dashboard)/strategies/[strategyId]/_api/get-statistics.ts
  app/(dashboard)/strategies/[strategyId]/_api/post-review.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-analysis-chart.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-analysis.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-reviews-data.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-statistics.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-post-review.ts
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/add-review.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/index.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-list.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/page.tsx
  app/(dashboard)/strategies/_ui/strategy-list/index.tsx
  mocks/handlers/strategy-details.ts
  shared/constants/count-per-page.ts
Labels: ✨ Feature

#180 [Feat] 회원가입 api 엔드포인트 수정 및 기능 구현
  app/(dashboard)/my/_api/get-favorite-strategy-list.ts
  app/(dashboard)/strategies/[strategyId]/_api/get-details-information.ts
  app/(dashboard)/strategies/_api/get-strategies.ts
  app/(landing)/signup/_api/email-auth.ts
  app/(landing)/signup/_api/signup.ts
  app/(landing)/signup/_hooks/custom/use-signup-email.ts
  app/(landing)/signup/_hooks/custom/use-signup-form.ts
  app/(landing)/signup/_ui/signup-complete-message/index.tsx
  app/(landing)/signup/information/page.module.scss
  app/(landing)/signup/information/page.tsx
  app/(landing)/signup/information/types.ts
  app/(landing)/signup/information/utils.ts
  app/layout.tsx
  app/test/client/page.tsx
  app/test/server/page.tsx
  app/test/ui/email-check-button/index.tsx
  app/test/ui/signup-button/index.tsx
  app/test/ui/styels.ts
  app/test/ui/title/index.tsx
  app/test/ui/withdraw-button/index.tsx
  mocks/browser.ts
  mocks/handlers.ts
  mocks/handlers/auth.ts
  mocks/handlers/index.ts
  mocks/handlers/post.ts
  mocks/handlers/strategies.ts
  mocks/handlers/strategy-details.ts
  mocks/handlers/user.ts
  mocks/index.ts
  mocks/server.ts
  next.config.mjs
  public/mockServiceWorker.js
  shared/providers/index.ts
  shared/providers/msw-Initializer.tsx
Labels: ✨ Feature

#185 [Feat] msw->스웨거api로 적용, 검색바 api 적용
  app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
  app/(dashboard)/strategies/[strategyId]/_api/get-details-information.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-details-information-data.ts
  app/(dashboard)/strategies/[strategyId]/page.tsx
  app/(dashboard)/strategies/_api/get-strategies-search.ts
  app/(dashboard)/strategies/_api/get-strategies.ts
  app/(dashboard)/strategies/_api/post-strategies.ts
  app/(dashboard)/strategies/_hooks/query/use-get-strategies-data.ts
  app/(dashboard)/strategies/_hooks/query/use-get-strategies-search.ts
  app/(dashboard)/strategies/_hooks/query/use-post-strategies.ts
  app/(dashboard)/strategies/_ui/search-bar/_store/use-searching-item-store.ts
  app/(dashboard)/strategies/_ui/search-bar/accordion-container.tsx
  app/(dashboard)/strategies/_ui/search-bar/accordion-panel.tsx
  app/(dashboard)/strategies/_ui/search-bar/algorithm-item.tsx
  app/(dashboard)/strategies/_ui/search-bar/index.tsx
  app/(dashboard)/strategies/_ui/search-bar/panel-mapping.ts
  app/(dashboard)/strategies/_ui/strategy-list/index.tsx
  shared/hooks/custom/use-pagination.ts
Labels: ✨ Feature

#184 [Feat] 답변하기 textarea 추가 퍼블리싱
  app/(dashboard)/my/questions/[questionId]/_ui/question-container/index.tsx
  app/(dashboard)/my/questions/[questionId]/_ui/question-container/styles.module.scss
  shared/ui/textarea/styles.module.scss
Labels: ✨ Feature

#190 [Feat] 로딩 페이지 및 스켈레톤 mixin 추가
  app/loading.module.scss
  app/loading.tsx
  shared/styles/base/_mixins.scss
  shared/ui/spinner/index.tsx
  shared/ui/spinner/styles.module.scss
Labels: ✨ Feature

#193 [Feat] 로그인, 구독 모달 추가
  app/(dashboard)/strategies/_ui/strategy-list/index.tsx
  app/(landing)/signup/information/page.tsx
  shared/ui/modal/index.tsx
  shared/ui/modal/modal.stories.tsx
  shared/ui/modal/signin-check-modal.tsx
  shared/ui/modal/styles.module.scss
  shared/ui/modal/subscribe-check-modal.tsx
Labels: ✨ Feature

#197 [HotFix] 로그인 엔드포인트 변경에 따른 코드 수정
  shared/api/auth.ts
Labels: 📬 API

#194 [Feat] number type 문자로 포맷
  app/(dashboard)/_ui/details-side-item/side-item.tsx
  app/(dashboard)/_ui/strategies-item/index.tsx
  shared/ui/table/statistics/index.tsx
  shared/ui/table/vertical/index.tsx
  shared/utils/format.ts
Labels: ✨ Feature

#198 [Feat] 구독 api & 확인 모달 적용
  app/(dashboard)/_ui/details-information/index.tsx
  app/(dashboard)/_ui/strategies-item/index.tsx
  app/(dashboard)/_ui/strategies-item/subscribe.tsx
  app/(dashboard)/_ui/subscriber-item/index.tsx
  app/(dashboard)/strategies/[strategyId]/_api/get-analysis-chart.ts
  app/(dashboard)/strategies/[strategyId]/_api/get-analysis.ts
  app/(dashboard)/strategies/[strategyId]/_api/get-details-information.ts
  app/(dashboard)/strategies/[strategyId]/_api/get-reviews.ts
  app/(dashboard)/strategies/[strategyId]/_api/get-statistics.ts
  app/(dashboard)/strategies/[strategyId]/_api/post-review.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-details-information-data.ts
  app/(dashboard)/strategies/[strategyId]/page.tsx
  app/(dashboard)/strategies/_api/get-subscribe.ts
  app/(dashboard)/strategies/_hooks/query/use-get-subscribe.ts
Labels: ✨ Feature

#202 [Design] 랜딩 페이지 반응형 스타일 적용
  app/(landing)/(home)/_ui/average-metrics-section/average-metrics-chart.tsx
  app/(landing)/(home)/_ui/average-metrics-section/index.tsx
  app/(landing)/(home)/_ui/average-metrics-section/styles.module.scss
  app/(landing)/(home)/_ui/hero-section/index.tsx
  app/(landing)/(home)/_ui/hero-section/styles.module.scss
  app/(landing)/(home)/_ui/top-favorite-section/styles.module.scss
  app/(landing)/(home)/_ui/top-sm-score-section/styles.module.scss
  app/(landing)/(home)/_ui/user-metrics-section/styles.module.scss
  shared/styles/base/_mixins.scss
Labels: 🎨 Design

#204 [Design] footer 반응형 디자인 적용
  shared/ui/footer/styles.module.scss
Labels: 🎨 Design

#209 [Rename] check-duplicate 파일 shared로 이동
  app/(landing)/signup/_hooks/custom/use-signup-email.ts
  app/(landing)/signup/_hooks/custom/use-signup-form.ts
  shared/api/.gitkeep
  shared/api/check-duplicate.ts
Labels: 🔨 Refactor

#208 [Fix] 랜딩 페이지 바로 함께하기 버튼 조건 처리
  app/(landing)/(home)/_ui/hero-section/index.tsx
Labels: 🐛 Bug

#210 [Bug] 검색바 호출 버그 개선 및 목록 디자인 그리드사이즈 수정
  app/(dashboard)/_ui/list-header/styles.module.scss
  app/(dashboard)/_ui/strategies-item/styles.module.scss
  app/(dashboard)/strategies/_api/get-strategies-search.ts
  app/(dashboard)/strategies/_api/get-subscribe.ts
  app/(dashboard)/strategies/_api/post-strategies.ts
  app/(dashboard)/strategies/_ui/search-bar/_store/use-searching-item-store.ts
  app/(dashboard)/strategies/_ui/search-bar/index.tsx
  app/(dashboard)/strategies/_ui/strategy-list/index.tsx
Labels: 🎨 Design, 🐛 Bug

#195 [Feat] admin 전력 페이지 완성
  app/(dashboard)/my/questions/[questionId]/_ui/question-container/index.tsx
  app/admin/strategies/_ui/shared/_api/get-presigned-url.ts
  app/admin/strategies/_ui/shared/_api/upload-file-with-presigned-url.ts
  app/admin/strategies/_ui/shared/_hooks/use-strategy-icon-post.ts
  app/admin/strategies/_ui/shared/file-input/index.tsx
  app/admin/strategies/_ui/shared/file-input/styles.module.scss
  app/admin/strategies/_ui/shared/manage-table/constant/index.ts
  app/admin/strategies/_ui/shared/manage-table/file-input/index.tsx
  app/admin/strategies/_ui/shared/manage-table/index.tsx
  app/admin/strategies/_ui/shared/manage-table/styles.module.scss
  app/admin/strategies/_ui/shared/manage-table/utils/add-index-to-data.tsx
  app/admin/strategies/_ui/stock/stock-manage/_api/get-stocks.ts
  app/admin/strategies/_ui/stock/stock-manage/_api/toggle-stock-active-state.ts
  app/admin/strategies/_ui/stock/stock-manage/_hooks/query/use-stocks-data.ts
  app/admin/strategies/_ui/stock/stock-manage/_hooks/query/use-toggle-trade-active-state.ts
  app/admin/strategies/_ui/stock/stock-manage/_ui/active-stock-manage-table.tsx
  app/admin/strategies/_ui/stock/stock-manage/_ui/inactive-stock-manage-table.tsx
  app/admin/strategies/_ui/stock/stock-manage/_ui/stock-active-state-toggle-button.tsx
  app/admin/strategies/_ui/stock/stock-manage/_ui/stock-post-button/index.tsx
  app/admin/strategies/_ui/stock/stock-manage/_ui/stock-post-button/styles.module.scss
  app/admin/strategies/_ui/stock/stock-manage/index.tsx
  app/admin/strategies/_ui/stock/stock-manage/styles.module.scss
  app/admin/strategies/_ui/stock/stock-manage/types.ts
  app/admin/strategies/_ui/trade/trade-manage/_api/get-trades.ts
  app/admin/strategies/_ui/trade/trade-manage/_api/toggle-trade-active-state.ts
  app/admin/strategies/_ui/trade/trade-manage/_hooks/query/use-toggle-trade-active-state.ts
  app/admin/strategies/_ui/trade/trade-manage/_hooks/query/use-trades-data.ts
  app/admin/strategies/_ui/trade/trade-manage/_ui/active-trade-manage-table.tsx
  app/admin/strategies/_ui/trade/trade-manage/_ui/inactive-trade-manage-table.tsx
  app/admin/strategies/_ui/trade/trade-manage/_ui/trade-active-state-toggle-button.tsx
  app/admin/strategies/_ui/trade/trade-manage/_ui/trade-post-button/index.tsx
  app/admin/strategies/_ui/trade/trade-manage/_ui/trade-post-button/styles.module.scss
  app/admin/strategies/_ui/trade/trade-manage/index.tsx
  app/admin/strategies/_ui/trade/trade-manage/styles.module.scss
  app/admin/strategies/_ui/trade/trade-manage/types.ts
  app/admin/strategies/page.module.scss
  app/admin/strategies/page.tsx
  next.config.mjs
  shared/ui/table/vertical/index.tsx
Labels: ✨ Feature

#216 [Design] 헤더 반응형 작업
  shared/ui/header/index.tsx
  shared/ui/header/styles.module.scss
Labels: 🎨 Design

#214 [Fix] strategies page category로 이름 수정
  app/admin/category/_ui/shared/_api/get-presigned-url.ts
  app/admin/category/_ui/shared/_api/upload-file-with-presigned-url.ts
  app/admin/category/_ui/shared/_hooks/use-category-icon-post.ts
  app/admin/category/_ui/shared/file-input/index.tsx
  app/admin/category/_ui/shared/file-input/styles.module.scss
  app/admin/category/_ui/shared/manage-table/constant/index.ts
  app/admin/category/_ui/shared/manage-table/file-input/index.tsx
  app/admin/category/_ui/shared/manage-table/index.tsx
  app/admin/category/_ui/shared/manage-table/styles.module.scss
  app/admin/category/_ui/shared/manage-table/utils/add-index-to-data.tsx
  app/admin/category/_ui/stock/stock-manage/_api/get-stocks.ts
  app/admin/category/_ui/stock/stock-manage/_api/toggle-stock-active-state.ts
  app/admin/category/_ui/stock/stock-manage/_hooks/query/use-stocks-data.ts
  app/admin/category/_ui/stock/stock-manage/_hooks/query/use-toggle-trade-active-state.ts
  app/admin/category/_ui/stock/stock-manage/_ui/active-stock-manage-table.tsx
  app/admin/category/_ui/stock/stock-manage/_ui/inactive-stock-manage-table.tsx
  app/admin/category/_ui/stock/stock-manage/_ui/stock-active-state-toggle-button.tsx
  app/admin/category/_ui/stock/stock-manage/_ui/stock-post-button/index.tsx
  app/admin/category/_ui/stock/stock-manage/_ui/stock-post-button/styles.module.scss
  app/admin/category/_ui/stock/stock-manage/index.tsx
  app/admin/category/_ui/stock/stock-manage/styles.module.scss
  app/admin/category/_ui/stock/stock-manage/types.ts
  app/admin/category/_ui/trade/trade-manage/_api/get-trades.ts
  app/admin/category/_ui/trade/trade-manage/_api/toggle-trade-active-state.ts
  app/admin/category/_ui/trade/trade-manage/_hooks/query/use-toggle-trade-active-state.ts
  app/admin/category/_ui/trade/trade-manage/_hooks/query/use-trades-data.ts
  app/admin/category/_ui/trade/trade-manage/_ui/active-trade-manage-table.tsx
  app/admin/category/_ui/trade/trade-manage/_ui/inactive-trade-manage-table.tsx
  app/admin/category/_ui/trade/trade-manage/_ui/trade-active-state-toggle-button.tsx
  app/admin/category/_ui/trade/trade-manage/_ui/trade-post-button/index.tsx
  app/admin/category/_ui/trade/trade-manage/_ui/trade-post-button/styles.module.scss
  app/admin/category/_ui/trade/trade-manage/index.tsx
  app/admin/category/_ui/trade/trade-manage/styles.module.scss
  app/admin/category/_ui/trade/trade-manage/types.ts
  app/admin/category/page.module.scss
  app/admin/category/page.tsx
  app/admin/strategies/page.tsx
Labels: 🐛 Bug

#225 [Design] 약관 페이지 여백 추가 및 폰트 사이즈 수정
  app/(landing)/privacy-terms/page.module.scss
  app/(landing)/terms-of-use/page.module.scss
  app/(landing)/terms-of-use/page.tsx
Labels: 🎨 Design

#223 [Feat] 대표 전략 통합 평균 지표 api 연결
  app/(landing)/(home)/_api/strategies-metrics.ts
  app/(landing)/(home)/_hooks/query/use-get-strategies-metrics.ts
  app/(landing)/(home)/_ui/average-metrics-section/average-metrics-chart.tsx
  app/(landing)/(home)/_ui/average-metrics-section/index.tsx
Labels: ✨ Feature

#220 [Feat] 리뷰 수정, 삭제 api 추가 & 안내모달 적용
  app/(dashboard)/strategies/[strategyId]/_api/delete-review.ts
  app/(dashboard)/strategies/[strategyId]/_api/patch-review.ts
  app/(dashboard)/strategies/[strategyId]/_api/post-review.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-delete-review.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-patch-review.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-post-review.ts
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/add-review.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/index.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-guide-modal.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-item.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-list.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/styles.module.scss
  app/(dashboard)/strategies/_ui/search-bar/range-container.tsx
Labels: ✨ Feature

#215 [Feat] admin users page 완성 - 1
  app/admin/_ui/admin-header/index.tsx
  app/admin/notices/page.module.scss
  app/admin/notices/page.tsx
  app/admin/notices/post/_ui/input-field/index.tsx
  app/admin/notices/post/_ui/input-field/styles.module.scss
  app/admin/notices/post/page.tsx
  app/admin/notices/tabledata.tsx
  app/admin/users/_api/delete-user.ts
  app/admin/users/_api/get-admin-users.ts
  app/admin/users/_api/patch-user-role.ts
  app/admin/users/_api/set-table-body.tsx
  app/admin/users/_hooks/query/use-admin-users.ts
  app/admin/users/_hooks/query/use-delete-user.ts
  app/admin/users/_hooks/query/use-patch-user-role.ts
  app/admin/users/_hooks/use-user-search-page.ts
  app/admin/users/_ui/role-select.tsx
  app/admin/users/_ui/user-delete-button.tsx
  app/admin/users/constants.ts
  app/admin/users/page.module.scss
  app/admin/users/page.tsx
  app/admin/users/types.ts
  shared/ui/header/index.tsx
  shared/ui/title/index.tsx
Labels: ✨ Feature

#227 [Feat] 로그인 전반적인 로직 수정 & 관리자 세션 만료 전 경고 모달 구현
  app/(landing)/signin/page.tsx
  app/layout.tsx
  shared/api/axios.ts
  shared/constants/auth.ts
  shared/hooks/custom/use-auth.ts
  shared/hooks/custom/use-session-expiry-warning.tsx
  shared/hooks/query/auth-queries.ts
  shared/lib/auth-tokens.ts
  shared/providers/auth-provider.tsx
  shared/stores/use-auth-store.ts
  shared/stores/use-modal-store.ts
  shared/stores/use-session-store.ts
  shared/ui/modal/session-extension-modal/index.tsx
  shared/ui/modal/session-extension-modal/styles.module.scss
  shared/utils/auth-path.ts
  shared/utils/token-utils.ts
Labels: ✨ Feature

#233 [Feat] 공지사항 페이지 퍼블리싱
  app/(landing)/notices/_ui/notice-table/index.tsx
  app/(landing)/notices/_ui/notice-table/styles.module.scss
  app/(landing)/notices/page.module.scss
  app/(landing)/notices/page.tsx
  shared/ui/table/vertical/index.tsx
Labels: ✨ Feature

#234 [Bug] 종목매매 아이콘 주석해제, 예외처리 추가 및 일부 스타일수정
  app/(dashboard)/_ui/analysis-container/analysis-chart.tsx
  app/(dashboard)/_ui/analysis-container/styles.module.scss
  app/(dashboard)/_ui/details-information/index.tsx
  app/(dashboard)/_ui/strategies-item/area-chart.tsx
  app/(dashboard)/_ui/strategies-item/index.tsx
  app/(dashboard)/_ui/strategies-item/strategies-icon.tsx
  app/(dashboard)/_ui/strategies-item/styles.module.scss
  app/(dashboard)/strategies/_api/get-subscribe.ts
  shared/ui/total-star/index.tsx
  shared/ui/total-star/styles.module.scss
Labels: 🎨 Design, 🐛 Bug

#229 [Feat] 문의하기 모달 & 문의 등록 성공 안내 모달 추가
  app/(dashboard)/_ui/details-side-item/index.tsx
  app/(dashboard)/_ui/details-side-item/side-item.tsx
  app/(dashboard)/strategies/[strategyId]/page.tsx
  shared/ui/input/styles.module.scss
  shared/ui/modal/add-question-modal.tsx
  shared/ui/modal/question-guide-modal.tsx
  shared/ui/modal/styles.module.scss
Labels: ✨ Feature

#241 [Utils] API response base interface 추가
  shared/types/response.ts
Labels: ✨ Feature

#242 [Feat] 문의 내역 불러오기 api 연결
  app/(dashboard)/my/questions/[questionId]/_ui/question-container/index.tsx
  app/(dashboard)/my/questions/[questionId]/_ui/question-detail-card/question-detail-card.stories.tsx
  app/(dashboard)/my/questions/[questionId]/_ui/question-detail-card/styles.module.scss
  app/(dashboard)/my/questions/_api/get-my-question-list.ts
  app/(dashboard)/my/questions/_api/get-question-details.ts
  app/(dashboard)/my/questions/_hooks/query/use-get-my-question-list.ts
  app/(dashboard)/my/questions/_hooks/query/use-get-question-details.ts
  app/(dashboard)/my/questions/_ui/question-card/index.tsx
  app/(dashboard)/my/questions/_ui/question-card/question-card.stories.tsx
  app/(dashboard)/my/questions/_ui/questions-tab-content/index.tsx
  app/(dashboard)/my/questions/_ui/questions-tab/index.tsx
  app/(dashboard)/my/questions/page.tsx
  shared/types/questions.ts
Labels: ✨ Feature

#219 [Feat] 마이페이지 프로필 컴포넌트 작업
  app/(dashboard)/my/profile/_ui/user-info/index.tsx
  app/(dashboard)/my/profile/_ui/user-info/styles.module.scss
  app/(dashboard)/my/profile/_ui/user-profile/index.tsx
  app/(dashboard)/my/profile/_ui/user-profile/styles.module.scss
  app/(dashboard)/my/profile/_ui/user-withdraw/index.tsx
  app/(dashboard)/my/profile/_ui/user-withdraw/styles.module.scss
  app/(dashboard)/my/profile/edit/page.tsx
  app/(dashboard)/my/profile/page.tsx
  app/(dashboard)/my/profile/withdraw/page.tsx
  public/icons/camera.svg
  public/icons/index.tsx
  shared/constants/path.ts
  shared/styles/stories/icons.stories.tsx
  shared/ui/avatar/avatar.stories.tsx
  shared/ui/avatar/index.tsx
  shared/ui/avatar/styles.module.scss
  shared/ui/button/button.stories.tsx
  shared/ui/input/index.tsx
  shared/ui/input/input.stories.tsx
  shared/ui/input/styles.module.scss
  shared/ui/link-button/link-button.stories.tsx
  shared/ui/page-not-found/index.tsx
Labels: ✨ Feature

#244 [Feat] NoticeDetail 컴포넌트 생성
  app/(landing)/notices/[noticeId]/detail/page.tsx
  app/(landing)/notices/_ui/notice-detail/index.tsx
  app/(landing)/notices/_ui/notice-detail/styles.module.scss
  app/(landing)/notices/_ui/notice-table/styles.module.scss
  app/(landing)/notices/page.tsx
  public/icons/download.svg
  public/icons/index.tsx
  shared/styles/stories/icons.stories.tsx
Labels: ✨ Feature

#246 [Feat] 일간분석 업로드 모달 및 기능 구현
  app/(dashboard)/_ui/analysis-container/analysis-content.tsx
  app/(dashboard)/_ui/strategies-item/index.tsx
  app/(dashboard)/_ui/strategies-item/styles.module.scss
  app/(dashboard)/my/_api/get-my-daily-analysis.ts
  app/(dashboard)/my/_api/post-daily-analysis.ts
  app/(dashboard)/my/_hooks/query/use-analysis-mutation.ts
  app/(dashboard)/my/_hooks/query/use-get-my-daily-analysis.ts
  app/(dashboard)/my/strategies/_ui/my-strategy-list/index.tsx
  app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
  package-lock.json
  package.json
  public/icons/index.tsx
  public/icons/modal-register.svg
  shared/types/strategy-data.ts
  shared/ui/modal/analysis-upload-modal/form/direct-input-form.tsx
  shared/ui/modal/analysis-upload-modal/form/excel-upload-form.tsx
  shared/ui/modal/analysis-upload-modal/form/styles.module.scss
  shared/ui/modal/analysis-upload-modal/index.tsx
  shared/ui/modal/analysis-upload-modal/styles.module.scss
  shared/ui/modal/index.tsx
  shared/ui/modal/styles.module.scss
  shared/utils/excel-utils.ts
Labels: ✨ Feature

#237 [Feat] 제안서, 일간분석 엑셀, 월간분석 엑셀 다운로드 api 추가 및 적용
  app/(dashboard)/_ui/analysis-container/analysis-content.tsx
  app/(dashboard)/_ui/details-information/index.tsx
  app/(dashboard)/_ui/details-information/strategy-name-box.tsx
  app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
  app/(dashboard)/strategies/[strategyId]/_api/get-analysis-download.ts
  app/(dashboard)/strategies/[strategyId]/_api/get-proposal-download.ts
  app/(dashboard)/strategies/[strategyId]/_api/helper-download-file.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-analysis-download.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-proposal-download.ts
  app/(dashboard)/strategies/[strategyId]/page.tsx
Labels: ✨ Feature

#245 [Feat] 전략 통계 "%", "일" 수치 표시 추가
  shared/ui/table/statistics/constant.ts
  shared/ui/table/statistics/index.tsx
Labels: ✨ Feature

#252 [Bug] 나의 전략 일간분석 테이블 데이터 넣어주는 로직 수정
  app/(dashboard)/_ui/analysis-container/analysis-content.tsx
  lefthook.yml
  shared/ui/table/vertical/index.tsx
Labels: 🐛 Bug

#254 [Feat] 문의 등록 api 추가 및 적용
  app/(dashboard)/_ui/details-side-item/details-side-item.stories.tsx
  app/(dashboard)/_ui/details-side-item/index.tsx
  app/(dashboard)/_ui/details-side-item/side-item.tsx
  app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
  app/(dashboard)/strategies/[strategyId]/_api/post-question.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-post-question.ts
  app/(dashboard)/strategies/[strategyId]/page.tsx
Labels: ✨ Feature

#256 [Feat] 마이페이지 프로필페이지 퍼블리싱
  app/(dashboard)/my/profile/_ui/user-info/index.tsx
  app/(dashboard)/my/profile/_ui/user-info/styles.module.scss
  app/(dashboard)/my/profile/_ui/user-profile/index.tsx
  app/(dashboard)/my/profile/_ui/user-profile/styles.module.scss
  app/(dashboard)/my/profile/page.module.scss
  app/(dashboard)/my/profile/page.tsx
  shared/constants/path.ts
Labels: ✨ Feature, 🎨 Design

#257 [Feat] 실계좌 이미지 등록 API 연동
  app/(dashboard)/_ui/analysis-container/account-content.tsx
  app/(dashboard)/_ui/analysis-container/styles.module.scss
  app/(dashboard)/my/_api/get-my-account-iamges.ts
  app/(dashboard)/my/_api/post-account-image.ts
  app/(dashboard)/my/_hooks/query/use-get-my-account-image.ts
  app/(dashboard)/my/_hooks/query/use-upload-account-images.ts
  shared/ui/modal/account-register-modal/index.tsx
  shared/ui/modal/account-register-modal/styles.module.scss
Labels: ✨ Feature

#263 [HotFix] 전략 분석 api 쿼리키 추가
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-analysis.ts
Labels: 🐛 Bug

#267 [Feat] 랜딩 페이지 사용자 지표 api 연동
  app/(landing)/(home)/_api/user-metrics.ts
  app/(landing)/(home)/_hooks/query/use-get-user-metrics.ts
  app/(landing)/(home)/_ui/user-metrics-section/index.tsx
  app/(landing)/(home)/types.ts
Labels: ✨ Feature

#265 [Feat] admin notice page 퍼블리싱
  app/admin/_ui/admin-header/index.tsx
  app/admin/_ui/admin-header/styles.module.scss
  app/admin/_ui/input-field/index.tsx
  app/admin/_ui/input-field/styles.module.scss
  app/admin/notices/_ui/notice-post-button/index.tsx
  app/admin/notices/_ui/notice-post-button/styles.module.scss
  app/admin/notices/page.module.scss
  app/admin/notices/page.tsx
  app/admin/notices/post/_api/post-notice.ts
  app/admin/notices/post/_hooks/use-notice-form.ts
  app/admin/notices/post/_hooks/use-notice-post.ts
  app/admin/notices/post/_ui/file-input/index.tsx
  app/admin/notices/post/_ui/file-input/styles.module.scss
  app/admin/notices/post/_ui/input-field/index.tsx
  app/admin/notices/post/page.module.scss
  app/admin/notices/post/page.tsx
  app/admin/notices/post/types.ts
  app/admin/notices/tabledata.tsx
  shared/ui/header/styles.module.scss
Labels: ✨ Feature

#268 [Feat] 나의 전략일때 구독 할 수 없는 경고 모달 적용
  app/(dashboard)/_ui/strategies-item/index.tsx
  app/(dashboard)/_ui/strategies-item/subscribe.tsx
  shared/hooks/custom/use-modal.ts
  shared/ui/modal/subscribe-warning-modal.tsx
Labels: ✨ Feature

#269 [Feat] 실계좌 이미지 삭제 api 연결
  app/(dashboard)/_ui/analysis-container/account-content.tsx
  app/(dashboard)/_ui/analysis-container/styles.module.scss
  app/(dashboard)/my/_api/post-account-image.ts
  app/(dashboard)/my/_hooks/query/use-delete-account-images.ts
Labels: 📬 API

#270 [Feat] 문의 답변 등록 기능 구현
  app/(dashboard)/my/questions/[questionId]/_ui/question-container/index.tsx
  app/(dashboard)/my/questions/_api/post-answer.ts
  app/(dashboard)/my/questions/_hooks/query/use-post-answer.ts
  app/(dashboard)/my/questions/_ui/questions-tab/index.tsx
  shared/types/questions.ts
Labels: ✨ Feature

#273 [Feat] 전략목록 스켈레톤 ui 추가 및 적용
  app/(dashboard)/_ui/strategies-item/skeleton/index.tsx
  app/(dashboard)/_ui/strategies-item/skeleton/styles.module.scss
  app/(dashboard)/strategies/_ui/search-bar/search-bar-skeleton/index.tsx
  app/(dashboard)/strategies/_ui/search-bar/search-bar-skeleton/styles.module.scss
  app/(dashboard)/strategies/_ui/strategy-list/index.tsx
  app/(dashboard)/strategies/loading.tsx
  app/(dashboard)/strategies/page.module.scss
  app/(dashboard)/strategies/page.tsx
Labels: ✨ Feature

#275 [Feat] 전략 상세 로딩 스켈레톤 추가 및 적용
  app/(dashboard)/_ui/details-side-item/side-skeleton/index.tsx
  app/(dashboard)/_ui/details-side-item/side-skeleton/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/loading.module.scss
  app/(dashboard)/strategies/[strategyId]/loading.tsx
  app/(dashboard)/strategies/[strategyId]/page.tsx
Labels: ✨ Feature

#278 [Feat] 파비콘 추가
  app/favicon.ico
  app/icon.svg
Labels: ✨ Feature

#283 [Feat] Spinner 가운데 정렬
  app/(landing)/(home)/_ui/user-metrics-section/index.tsx
  app/(landing)/(home)/_ui/user-metrics-section/styles.module.scss
  shared/ui/spinner/index.tsx
  shared/ui/spinner/styles.module.scss
Labels: ✨ Feature

#285 [Feat] 구독한 전략 없을때 문구 및 스켈레톤 UI 적용
  app/(dashboard)/my/favorites/_ui/favorite-strategy-list/index.tsx
  app/(dashboard)/my/favorites/_ui/favorite-strategy-list/styles.module.scss
  app/(dashboard)/my/favorites/page.tsx
Labels: ✨ Feature

#286 [Feat] 이메일 찾기, 비밀번호 찾기 모달 및 기능 구현
  app/(landing)/signin/page.tsx
  app/(landing)/signin/styles.module.scss
  shared/api/find-credentials.ts
  shared/hooks/custom/use-auth.ts
  shared/hooks/custom/use-reset-password.ts
  shared/hooks/query/auth-queries.ts
  shared/hooks/query/use-find-credentials.ts
  shared/ui/modal/find-email-modal/index.tsx
  shared/ui/modal/find-email-modal/styles.module.scss
  shared/ui/modal/find-password-modal/index.tsx
  shared/ui/modal/find-password-modal/styles.module.scss
Labels: 📬 API, ✨ Feature

#290 [Bug] 회원가입 완료 메시지가 바로 뜨지 않는 오류 해결
  app/(landing)/signup/complete/page.tsx
Labels: 🐛 Bug

#293 [Fix] params수정
  app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
  app/(dashboard)/strategies/[strategyId]/page.tsx
  shared/ui/modal/subscribe-check-modal.tsx
Labels: ✨ Feature

#291 [Feat] 내전략일때 전략관리페이지로 이동버튼 추가
  app/(dashboard)/_ui/details-side-item/side-item.tsx
  app/(dashboard)/_ui/details-side-item/styles.module.scss
Labels: ✨ Feature

#288 [Feat] 프로필 get요청, 공지사항 상세보기 get 요청 API 연동
  app/(dashboard)/my/_api/get-profile.ts
  app/(dashboard)/my/_hooks/query/use-get-profile.ts
  app/(dashboard)/my/profile/_ui/user-info/index.tsx
  app/(dashboard)/my/profile/_ui/user-info/types.ts
  app/(dashboard)/my/profile/_ui/user-info/utils.ts
  app/(dashboard)/my/profile/edit/page.tsx
  app/(dashboard)/my/profile/page.tsx
  app/(landing)/notices/[noticeId]/detail/page.tsx
  app/(landing)/notices/_api/get-notice-detail.ts
  app/(landing)/notices/_hooks/use-notice-detail.ts
  app/(landing)/notices/_ui/notice-detail/index.tsx
  shared/utils/validation.ts
Labels: 📬 API, ✨ Feature

#294 feat: 관리자 사용자 페이지 완성
  app/admin/users/_ui/user-delete-button.tsx
  app/admin/users/page.tsx
Labels: ✨ Feature

#300 [Fix] 아이콘 사이즈 배율에 맞게 수정
  app/(dashboard)/_ui/strategies-item/strategies-icon.tsx
  app/(dashboard)/_ui/strategies-item/styles.module.scss
Labels: 🎨 Design

#299 [Refactor] 스켈레톤 loading파일이 아닌 일반파일로 수정
  app/(dashboard)/strategies/[strategyId]/_ui/details-skeleton/index.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/details-skeleton/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/page.tsx
  app/(dashboard)/strategies/loading.tsx
  app/(dashboard)/strategies/page.tsx
Labels: 🔨 Refactor

#297 [Feat] 관리자 전략 페이지 완성
  app/admin/_ui/admin-post-button/index.tsx
  app/admin/_ui/admin-post-button/styles.module.scss
  app/admin/_ui/file-input/index.tsx
  app/admin/_ui/file-input/styles.module.scss
  app/admin/strategies/_api/get-strategies.ts
  app/admin/strategies/_api/patch-strategy-approval.ts
  app/admin/strategies/_api/set-admin-strategies-table-body.tsx
  app/admin/strategies/_hooks/query/use-patch-strategy-approval.ts
  app/admin/strategies/_hooks/query/use-strategies-data.ts
  app/admin/strategies/_hooks/use-admin-strategies-page.ts
  app/admin/strategies/_ui/admin-strategies-approve-td/index.tsx
  app/admin/strategies/_ui/admin-strategies-approve-td/styles.module.scss
  app/admin/strategies/_ui/admin-strategy-public-select.tsx
  app/admin/strategies/constants.ts
  app/admin/strategies/page.module.scss
  app/admin/strategies/page.tsx
  app/admin/strategies/types.ts
Labels: ✨ Feature

#302 [Feat] 분석 탭에 데이터 없을 경우 ui 통일하여 추가
  app/(dashboard)/_ui/analysis-container/analysis-content.tsx
  app/(dashboard)/_ui/analysis-container/statistics-content.tsx
  app/(dashboard)/_ui/analysis-container/styles.module.scss
  app/(dashboard)/_ui/details-information/styles.module.scss
  app/(dashboard)/my/_hooks/query/use-get-my-daily-analysis.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-analysis.ts
Labels: ✨ Feature

#308 [Feat] 전략등록 페이지 퍼블리싱 및 API 연결
  app/(dashboard)/my/_api/add-strategy.ts
  app/(dashboard)/my/_constants/investment-amount.ts
  app/(dashboard)/my/_hooks/query/use-add-strategy.ts
  app/(dashboard)/my/strategies/add/page.tsx
  app/(dashboard)/my/strategies/add/styles.module.scss
Labels: 📬 API, ✨ Feature

#307 [Fix] admin category에서 Suspense가 적용되지 않던 부분과 axiosInstance를 사용하지 않던 곳들을 찾아 교정
  app/admin/category/_ui/shared/_api/get-presigned-url.ts
  app/admin/category/_ui/shared/_api/upload-file-with-presigned-url.ts
  app/admin/category/_ui/shared/file-input/index.tsx
  app/admin/category/_ui/shared/file-input/styles.module.scss
  app/admin/category/_ui/shared/manage-table/file-input/index.tsx
  app/admin/category/_ui/shared/manage-table/index.tsx
  app/admin/category/_ui/stock/stock-manage/_api/get-stocks.ts
  app/admin/category/_ui/stock/stock-manage/_api/set-admin-stock-manage-table-data.tsx
  app/admin/category/_ui/stock/stock-manage/_api/toggle-stock-active-state.ts
  app/admin/category/_ui/stock/stock-manage/_hooks/query/use-stocks-data.ts
  app/admin/category/_ui/stock/stock-manage/_ui/active-stock-manage-table.tsx
  app/admin/category/_ui/stock/stock-manage/_ui/inactive-stock-manage-table.tsx
  app/admin/category/_ui/stock/stock-manage/_ui/stock-post-button/index.tsx
  app/admin/category/_ui/trade/trade-manage/_api/get-trades.ts
  app/admin/category/_ui/trade/trade-manage/_api/set-admin-trade-manage-table-data.tsx
  app/admin/category/_ui/trade/trade-manage/_api/toggle-trade-active-state.ts
  app/admin/category/_ui/trade/trade-manage/_hooks/query/use-trades-data.ts
  app/admin/category/_ui/trade/trade-manage/_ui/active-trade-manage-table.tsx
  app/admin/category/_ui/trade/trade-manage/_ui/inactive-trade-manage-table.tsx
  app/admin/category/_ui/trade/trade-manage/_ui/trade-post-button/index.tsx
  app/admin/notices/post/_ui/file-input/index.tsx
  app/admin/notices/post/_ui/file-input/styles.module.scss
  app/admin/notices/post/page.tsx
  shared/ui/table/vertical/index.tsx
Labels: 🐛 Bug
