Repository FC-DEV-FinalProject/FinalProject_team3_FE, pull requests merged in 2024-11, with the labels that each got.

#5 [Settings] 기본 폴더 구조 세팅
  app/(home)/layout.tsx
  app/(home)/page.module.css
  app/(home)/page.tsx
  app/(home)/ui/.gitkeep
  lefthook.yml
  shared/api/.gitkeep
  shared/hooks/custom/.gitkeep
  shared/hooks/query/.gitkeep
  shared/stores/.gitkeep
  shared/styles/reset.scss
  shared/ui/button/index.tsx
  shared/ui/button/styles.module.scss
  tsconfig.json
Labels: ⚙ Settings

#10 [Settings] import 정렬 순서 규칙 설정
  .prettierrc
  package-lock.json
  package.json
Labels: ⚙ Settings

#9 [Feature] TanStack Query 세팅
  app/layout.tsx
  package-lock.json
  package.json
  shared/providers/index.ts
  shared/providers/react-query/query-client.ts
  shared/providers/react-query/query-provider.tsx
Labels: ✨ Feature

#13 [Design] 기본 스타일 세팅
  .storybook/main.ts
  .storybook/preview.ts
  app/(home)/layout.tsx
  app/fonts.ts
  app/layout.tsx
  next.config.mjs
  package-lock.json
  package.json
  public/fonts/PretendardVariable.woff2
  shared/providers/react-query/query-client.ts
  shared/providers/react-query/query-provider.tsx
  shared/styles/base/_functions.scss
  shared/styles/base/_mixins.scss
  shared/styles/base/_reset.scss
  shared/styles/base/_variables.scss
  shared/styles/global.scss
  shared/styles/reset.scss
  shared/styles/stories/colors.stories.tsx
  shared/styles/stories/fonts.stories.tsx
Labels: ⚙ Settings, 🎨 Design

#17 [Setting] route 구조 세팅
  app/(dashboard)/.gitkeep
  app/(dashboard)/admin/.gitkeep
  app/(dashboard)/admin/category/.gitkeep
  app/(dashboard)/admin/notices/.gitkeep
  app/(dashboard)/admin/users/.gitkeep
  app/(dashboard)/my/.gitkeep
  app/(dashboard)/my/favorites/.gitkeep
  app/(dashboard)/my/questions/.gitkeep
  app/(dashboard)/my/strategies/.gitkeep
  app/(dashboard)/my/strategies/manage/[strategyId]/.gitkeep
  app/(dashboard)/strategies/.gitkeep
  app/(dashboard)/strategies/[strategyId]/.gitkeep
  app/(dashboard)/traders/.gitkeep
  app/(dashboard)/traders/[traderId]/.gitkeep
  app/(landing)/(home)/page.module.css
  app/(landing)/(home)/page.tsx
  app/(landing)/(home)/ui/.gitkeep
  app/(landing)/layout.tsx
  app/(landing)/signin/.gitkeep
  app/(landing)/signup/.gitkeep
Labels: ⚙ Settings, 📃 Docs

#21 [settings] api 요청시 경로 rewriter 설정
  next.config.mjs
Labels: ⚙ Settings

#26 [Feat] 공통 테이블 컴포넌트 & 통계 테이블 컴포넌트
  .gitignore
  app/(dashboard)/strategies/page.tsx
  shared/types/strategy-details-data.ts
  shared/ui/table/statistics/inKorean.ts
  shared/ui/table/statistics/index.tsx
  shared/ui/table/statistics/statistics-table.stories.tsx
  shared/ui/table/statistics/statistics.module.scss
  shared/ui/table/vertical/index.tsx
  shared/ui/table/vertical/table.stories.tsx
  shared/ui/table/vertical/vertical.module.scss
Labels: ✨ Feature, 🎨 Design

#36 [settings] Storybook 배포 설정
  .github/workflows/chromatic.yml
Labels: ⚙ Settings

#38 [settings] typescale mixin들 추가
  shared/styles/base/_mixins.scss
Labels: ⚙ Settings

#41 [Feat] 페이지네이션 컴포넌트 추가
  .storybook/main.ts
  next.config.mjs
  package-lock.json
  package.json
  shared/types/svg.d.ts
  shared/ui/pagination/index.tsx
  shared/ui/pagination/pagination.module.scss
  shared/ui/pagination/pagination.stories.tsx
  tsconfig.json
Labels: ✨ Feature

#42 [Design] 아이콘 파일 수정 및 추가
  app/(dashboard)/_ui/navigation.tsx
  public/icons/bookmark-outline.svg
  public/icons/bookmark.svg
  public/icons/daily-graph.svg
  public/icons/index.tsx
  public/icons/monthly-graph.svg
  public/icons/open.svg
  public/icons/search.svg
  public/icons/star.svg
  public/icons/statistics.svg
  shared/styles/stories/colors.stories.tsx
  shared/styles/stories/fonts.stories.tsx
  shared/styles/stories/icons.stories.tsx
Labels: 🎨 Design

#44 [Feat] 테이블 컴포넌트 수정사항 적용
  shared/ui/table/statistics/index.tsx
  shared/ui/table/statistics/statistics-table.stories.tsx
  shared/ui/table/statistics/styles.module.scss
  shared/ui/table/vertical/index.tsx
  shared/ui/table/vertical/styles.module.scss
  shared/ui/table/vertical/table.stories.tsx
Labels: ✨ Feature

#50 [Bug] 사이드 네비게이션 오류 수정
  shared/constants/path.ts
  shared/ui/side-navigation/nav-link-item.tsx
  shared/ui/side-navigation/styles.module.scss
Labels: 🐛 Bug

#46 [Feat] Tabs 컴포넌트 추가
  shared/ui/tabs/index.tsx
  shared/ui/tabs/styles.module.scss
  shared/ui/tabs/tab-button.tsx
  shared/ui/tabs/tabs.stories.tsx
Labels: ✨ Feature

#51 [Feat] 총별점 컴포넌트 추가
  public/icons/star.svg
  shared/ui/total-star/index.tsx
  shared/ui/total-star/star-icon.tsx
  shared/ui/total-star/styles.module.scss
  shared/ui/total-star/total-star.stories.tsx
Labels: ✨ Feature, 🎨 Design

#34 [Feat] 회원가입 Step 컴포넌트 추가
  app/(landing)/signup/_ui/step/index.tsx
  app/(landing)/signup/_ui/step/step-item.tsx
  app/(landing)/signup/_ui/step/styles.module.scss
  app/(landing)/signup/complete/page.tsx
  app/(landing)/signup/information/page.tsx
  app/(landing)/signup/terms-of-use/page.tsx
  app/(landing)/signup/user-type/page.tsx
  shared/constants/path.ts
  shared/stores/use-step-history-store.tsx
  shared/styles/global.scss
Labels: ✨ Feature, 🎨 Design

#57 [Feat] 아바타 컴포넌트 추가
  public/icons/profile.svg
  shared/ui/avatar/avatar.stories.tsx
  shared/ui/avatar/index.tsx
  shared/ui/avatar/styles.module.scss
Labels: ✨ Feature

#58 [Feat] Input 공통 컴포넌트 생성 및 유효성 검사 함수 추가
  package-lock.json
  shared/constants/error-messages.ts
  shared/types/error-message.ts
  shared/ui/input/index.tsx
  shared/ui/input/input.stories.tsx
  shared/ui/input/styles.module.scss
  shared/ui/search-input/index.tsx
  shared/ui/search-input/search-input.stories.tsx
  shared/ui/search-input/styles.module.scss
  shared/ui/textarea/index.tsx
  shared/ui/textarea/styles.module.scss
  shared/ui/textarea/textarea.stories.tsx
  shared/utils/validation.ts
Labels: ✨ Feature

#60 [Feat] 회원가입 유형 선택 페이지
  app/(landing)/signup/_stores/use-signup-store.ts
  app/(landing)/signup/_ui/step/styles.module.scss
  app/(landing)/signup/_ui/user-type-card/index.tsx
  app/(landing)/signup/_ui/user-type-card/styles.module.scss
  app/(landing)/signup/user-type/page.module.scss
  app/(landing)/signup/user-type/page.tsx
  shared/styles/global.scss
  shared/types/user.ts
Labels: ✨ Feature

#61 [Feature] sm 스코어 컴포넌트 추가
  app/(landing)/(home)/_ui/.gitkeep
  app/(landing)/(home)/_ui/line-chart/index.tsx
  app/(landing)/(home)/_ui/sm-score-card/index.tsx
  app/(landing)/(home)/_ui/sm-score-card/sm-score-card.stories.tsx
  app/(landing)/(home)/_ui/sm-score-card/styles.module.scss
  package-lock.json
  package.json
  shared/styles/base/_mixins.scss
Labels: ✨ Feature

#64 [Design] 페이지 레이아웃 공통 스타일 추가
  app/(dashboard)/layout.tsx
  app/(landing)/layout.tsx
  app/(landing)/signup/_ui/step/styles.module.scss
  app/admin/layout.tsx
  shared/styles/base/_reset.scss
  shared/styles/base/_variables.scss
  shared/styles/global.scss
  shared/ui/side-navigation/styles.module.scss
Labels: 🎨 Design

#67 [Feat] 전략 리스트 아이템 컴포넌트 추가
  app/(dashboard)/_ui/strategies-item/area-chart.tsx
  app/(dashboard)/_ui/strategies-item/index.tsx
  app/(dashboard)/_ui/strategies-item/strategies-icon.tsx
  app/(dashboard)/_ui/strategies-item/strategies-item.stories.tsx
  app/(dashboard)/_ui/strategies-item/strategies-summary.tsx
  app/(dashboard)/_ui/strategies-item/styles.module.scss
  app/(dashboard)/_ui/strategies-item/subscribe.tsx
  public/icons/bookmark-outline.svg
  public/icons/bookmark.svg
  shared/types/strategy-details-data.ts
Labels: ✨ Feature, 🎨 Design

#65 [Feat] 회원가입 완료 페이지 구현
  app/(landing)/signup/_stores/use-signup-store.ts
  app/(landing)/signup/_ui/signup-complete-message/index.tsx
  app/(landing)/signup/_ui/signup-complete-message/styles.module.scss
  app/(landing)/signup/_ui/step/step-item.tsx
  app/(landing)/signup/_ui/step/styles.module.scss
  app/(landing)/signup/complete/page.module.scss
  app/(landing)/signup/complete/page.tsx
  shared/styles/base/_mixins.scss
Labels: ✨ Feature

#80 [Feat] 대표 전략 통합 평균 지표 컴포넌트
  app/(landing)/(home)/_ui/average-metrics-container/average-metrics-chart.tsx
  app/(landing)/(home)/_ui/average-metrics-container/average-metrics.stories.tsx
  app/(landing)/(home)/_ui/average-metrics-container/index.tsx
  app/(landing)/(home)/_ui/average-metrics-container/styles.module.scss
  shared/styles/global.scss
Labels: ✨ Feature

#76 [Feat] Header 컴포넌트 추가
  public/images/index.ts
  shared/styles/base/_variables.scss
  shared/ui/button/index.tsx
  shared/ui/header/_ui/header-links/index.tsx
  shared/ui/header/back-header/back-header.stories.tsx
  shared/ui/header/back-header/index.tsx
  shared/ui/header/back-header/styles.module.scss
  shared/ui/header/index.tsx
  shared/ui/header/logo-header/index.tsx
  shared/ui/header/logo-header/logo-header.stories.tsx
  shared/ui/header/styles.module.scss
  shared/ui/link-button/link-button.stories.tsx
  shared/ui/logo/index.tsx
  shared/ui/logo/styles.module.scss
Labels: ✨ Feature

#86 [Feat] 전략상세 사이드정보 아이템 컴포넌트, 스토리북 추가
  app/(dashboard)/strategies/[strategyId]/_ui/details-side-item/details-side-item.stories.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/details-side-item/index.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/details-side-item/side-item.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/details-side-item/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/page.tsx
Labels: ✨ Feature, 🎨 Design

#82 [Feat] 전략 소개 컴포넌트, 스토리북 추가
  app/(dashboard)/strategies/[strategyId]/_ui/introduction/index.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/introduction/introduction.stories.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/introduction/styles.module.scss
  public/icons/close.svg
  public/icons/index.tsx
  public/icons/open.svg
  shared/styles/stories/icons.stories.tsx
Labels: ✨ Feature, 🎨 Design

#89 Common Title 컴포넌트 추가
  shared/ui/header/back-header/back-header.stories.tsx
  shared/ui/header/back-header/index.tsx
  shared/ui/header/logo-header/logo-header.stories.tsx
  shared/ui/title/index.tsx
  shared/ui/title/styles.module.scss
  shared/ui/title/title.stories.tsx
  shared/utils/storybook-mock-contents.tsx
Labels: ✨ Feature

#94 [Feat] 랜딩 페이지 Hero, UserMetrics 섹션 퍼블리싱
  app/(landing)/(home)/_ui/hero-section/index.tsx
  app/(landing)/(home)/_ui/hero-section/styles.module.scss
  app/(landing)/(home)/_ui/home-subtitle/index.tsx
  app/(landing)/(home)/_ui/home-subtitle/styles.module.scss
  app/(landing)/(home)/_ui/metric-card/index.tsx
  app/(landing)/(home)/_ui/metric-card/styles.module.scss
  app/(landing)/(home)/_ui/user-metrics-section/index.tsx
  app/(landing)/(home)/_ui/user-metrics-section/styles.module.scss
  app/(landing)/(home)/page.tsx
  next.config.mjs
  shared/ui/logo/styles.module.scss
  shared/ui/side-navigation/styles.module.scss
Labels: ✨ Feature

#91 [Feat] 회원가입 약관동의 페이지 및 회원가입 단계별 접근 제어 기능 구현
  app/(landing)/signup/_constants/cookies.ts
  app/(landing)/signup/_lib/cookies.ts
  app/(landing)/signup/_stores/use-signup-store.ts
  app/(landing)/signup/_ui/user-type-card/index.tsx
  app/(landing)/signup/complete/page.tsx
  app/(landing)/signup/information/page.tsx
  app/(landing)/signup/terms-of-use/_hooks/use-terms-check.ts
  app/(landing)/signup/terms-of-use/_ui/terms-container/index.tsx
  app/(landing)/signup/terms-of-use/_ui/terms-container/styles.module.scss
  app/(landing)/signup/terms-of-use/_ui/terms/investor-terms.tsx
  app/(landing)/signup/terms-of-use/_ui/terms/privacy-terms.tsx
  app/(landing)/signup/terms-of-use/_ui/terms/styles.module.scss
  app/(landing)/signup/terms-of-use/_ui/terms/trader-terms.tsx
  app/(landing)/signup/terms-of-use/page.module.scss
  app/(landing)/signup/terms-of-use/page.tsx
  app/(landing)/signup/user-type/page.tsx
  middleware.ts
  middleware/signup.ts
  next.config.mjs
  shared/styles/base/_variables.scss
  shared/ui/check-box/index.tsx
  shared/ui/check-box/styles.module.scss
Labels: ✨ Feature

#87 [Feat] 트레이더 리스트 카드 컴포넌트 구현
  shared/ui/traders-list-card/index.tsx
  shared/ui/traders-list-card/styles.module.scss
  shared/ui/traders-list-card/traders-list-card.stories.tsx
Labels: ✨ Feature

#39 [Feat] Select 컴포넌트 추가
  shared/ui/dropdown/hooks/use-dropdown-context.ts
  shared/ui/dropdown/hooks/use-dropdown.ts
  shared/ui/dropdown/index.tsx
  shared/ui/dropdown/option/range-option.tsx
  shared/ui/dropdown/styles.module.scss
  shared/ui/dropdown/types.ts
  shared/ui/select/hooks/useSelect.ts
  shared/ui/select/index.tsx
  shared/ui/select/select.stories.tsx
Labels: ✨ Feature

#106 [Refactor] 트레이더 리스트 카드 컴포넌트 코드 수정
  shared/ui/traders-list-card/index.tsx
  shared/ui/traders-list-card/styles.module.scss
  shared/ui/traders-list-card/traders-list-card.stories.tsx
Labels: 🔨 Refactor

#97 [Feat] 전략 상세 분석 차트 컴포넌트
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/analysis-chart.stories.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/analysis-chart.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/index.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/yaxis-options.ts
Labels: ✨ Feature, 🎨 Design

#108 [Refactor] Input 아이콘 크기 지정 및 로직 추가
  shared/ui/input/index.tsx
  shared/ui/input/styles.module.scss
  shared/ui/search-input/index.tsx
  shared/ui/search-input/styles.module.scss
  shared/ui/textarea/index.tsx
  shared/ui/textarea/styles.module.scss
Labels: 🔨 Refactor

#103 [Feat] 랜딩 페이지 퍼블리싱
  app/(landing)/(home)/_ui/average-metrics-section/average-metrics-chart.tsx
  app/(landing)/(home)/_ui/average-metrics-section/average-metrics.stories.tsx
  app/(landing)/(home)/_ui/average-metrics-section/index.tsx
  app/(landing)/(home)/_ui/average-metrics-section/styles.module.scss
  app/(landing)/(home)/_ui/line-chart/index.tsx
  app/(landing)/(home)/_ui/top-favorite-section/index.tsx
  app/(landing)/(home)/_ui/top-favorite-section/styles.module.scss
  app/(landing)/(home)/_ui/top-sm-score-section/index.tsx
  app/(landing)/(home)/_ui/top-sm-score-section/styles.module.scss
  app/(landing)/(home)/_ui/top-strategy-card/index.tsx
  app/(landing)/(home)/_ui/top-strategy-card/styles.module.scss
  app/(landing)/(home)/_ui/top-strategy-card/top-favorite-card.tsx
  app/(landing)/(home)/_ui/top-strategy-card/top-sm-score-card.tsx
  app/(landing)/(home)/_ui/top-strategy-card/types.ts
  app/(landing)/(home)/page.tsx
  shared/styles/global.scss
Labels: ✨ Feature

#113 [fix] select 컴포넌트 option이 레이아웃에 영향을 끼치는 버그 수정 및 편의성 개선
  shared/styles/base/_variables.scss
  shared/ui/dropdown/index.tsx
  shared/ui/dropdown/styles.module.scss
  shared/ui/dropdown/types.ts
Labels: 🐛 Bug

#70 [Feat] Modal 컴포넌트 구현 및 SVG 아이콘 추가
  app/layout.tsx
  public/icons/index.tsx
  public/icons/modal-alert.svg
  public/icons/modal-check.svg
  public/icons/modal-subscribe.svg
  public/icons/register.svg
  shared/constants/modal-messages.ts
  shared/hooks/custom/use-modal.ts
  shared/styles/base/_variables.scss
  shared/styles/stories/icons.stories.tsx
  shared/ui/modal/index.tsx
  shared/ui/modal/modal.stories.tsx
  shared/ui/modal/styles.module.scss
Labels: ✨ Feature

#105 [Feat] 로그인 페이지 퍼블리싱 및 MSW를 활용한 기능 구현
  app/(dashboard)/_ui/navigation.tsx
  app/(landing)/layout.tsx
  app/(landing)/signin/page.tsx
  app/(landing)/signin/styles.module.scss
  app/(landing)/signup/_lib/cookies.ts
  app/(landing)/signup/_ui/signup-complete-message/index.tsx
  app/(landing)/signup/_ui/user-type-card/index.tsx
  mocks/handlers.ts
  mocks/handlers/auth.ts
  mocks/handlers/index.ts
  package-lock.json
  package.json
  shared/api/auth.ts
  shared/api/axios.ts
  shared/api/user.ts
  shared/constants/auth.ts
  shared/constants/error-messages.ts
  shared/constants/path.ts
  shared/hooks/custom/use-auth.ts
  shared/hooks/query/auth-queries.ts
  shared/lib/auth-tokens.ts
  shared/stores/use-auth-store.ts
  shared/types/auth.ts
  shared/types/user.ts
  shared/ui/button/index.tsx
  shared/ui/check-box/index.tsx
  shared/ui/check-box/styles.module.scss
  shared/ui/input/index.tsx
  shared/ui/logo/styles.module.scss
  shared/ui/side-navigation/user-navigation.tsx
  shared/utils/token-utils.ts
  shared/utils/validation.ts
Labels: ✨ Feature, 🎨 Design

#112 [Feat] 리뷰 컴포넌트
  app/(dashboard)/strategies/[strategyId]/_api/get-details-information.ts
  app/(dashboard)/strategies/[strategyId]/_api/get-reviews.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-details-information-data.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-reviews-data.ts
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/add-review.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/index.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-item.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-list.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/_ui/star-rating/index.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/star-rating/star-rating.stories.tsx
  app/(dashboard)/strategies/[strategyId]/page.tsx
  app/(dashboard)/strategies/_hooks/query/use-get-strategies-data.ts
  mocks/handlers/strategy-details.ts
  shared/ui/textarea/index.tsx
  shared/ui/total-star/index.tsx
  shared/ui/total-star/styles.module.scss
Labels: ✨ Feature

#116 [Feat] Footer 컴포넌트 추가 및 Header 수정
  app/(landing)/layout.tsx
  public/images/text-logo.svg
  shared/constants/path.ts
  shared/ui/footer/footer-logo.tsx
  shared/ui/footer/index.tsx
  shared/ui/footer/styles.module.scss
  shared/ui/header/styles.module.scss
Labels: ✨ Feature

#123 [Feat] 구독자 수 보여주는 컴포넌트 추가
  app/(dashboard)/strategies/[strategyId]/_ui/subscriber-item/index.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/subscriber-item/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/page.tsx
Labels: ✨ Feature

#122 [Feat] page-not-found 컴포넌트
  app/not-found.tsx
  public/images/index.ts
  public/images/page-not-found-img.svg
  shared/ui/page-not-found/index.tsx
  shared/ui/page-not-found/page-not-found.stories.tsx
  shared/ui/page-not-found/styles.module.scss
Labels: ✨ Feature

#124 [Feat] 전략 상세 분석 컴포넌트 추가
  app/(dashboard)/_ui/details-information/index.tsx
  app/(dashboard)/_ui/details-information/invest-information.tsx
  app/(dashboard)/_ui/details-information/percentage.tsx
  app/(dashboard)/_ui/details-information/strategy-name-box.tsx
  app/(dashboard)/_ui/details-information/styles.module.scss
  app/(dashboard)/_ui/details-side-item/details-side-item.stories.tsx
  app/(dashboard)/_ui/details-side-item/index.tsx
  app/(dashboard)/_ui/details-side-item/side-item.tsx
  app/(dashboard)/_ui/details-side-item/styles.module.scss
  app/(dashboard)/_ui/introduction/index.tsx
  app/(dashboard)/_ui/introduction/introduction.stories.tsx
  app/(dashboard)/_ui/introduction/styles.module.scss
  app/(dashboard)/_ui/list-header/index.tsx
  app/(dashboard)/_ui/list-header/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/account-content.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/analysis-chart.stories.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/analysis-chart.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/analysis-content.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/example.ts
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/index.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/statistics-content.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/tabs-width-table.tsx
  app/(dashboard)/strategies/[strategyId]/page.tsx
  app/(dashboard)/strategies/_ui/strategy-list/index.tsx
  shared/ui/header/back-header/index.tsx
  shared/ui/select/index.tsx
  shared/ui/table/statistics/in-korean.ts
  shared/ui/table/statistics/index.tsx
  shared/ui/tabs/styles.module.scss
Labels: ✨ Feature

#120 [Feat] 트레이더 목록 페이지 퍼블리싱
  app/(dashboard)/traders/page.module.scss
  app/(dashboard)/traders/page.tsx
  public/mockServiceWorker.js
  shared/ui/dropdown/index.tsx
  shared/ui/dropdown/styles.module.scss
Labels: ✨ Feature

#129 [Feat] Input 에러메시지 컴포넌트 분리 및 ref속성 추가
  shared/ui/error-messages/error-messages.stories.tsx
  shared/ui/error-messages/index.tsx
  shared/ui/error-messages/styles.module.scss
  shared/ui/input/index.tsx
  shared/ui/input/input.stories.tsx
  shared/ui/input/styles.module.scss
  shared/ui/search-input/index.tsx
Labels: ✨ Feature

#132 [Feat] 회원가입 정보입력 페이지 퍼블리싱 및 기능 구현
  app/(landing)/signup/.gitkeep
  app/(landing)/signup/_api/check-duplicate.ts
  app/(landing)/signup/_api/email-auth.ts
  app/(landing)/signup/_api/signup.ts
  app/(landing)/signup/_constants/signup.ts
  app/(landing)/signup/_hooks/custom/use-signup-email.ts
  app/(landing)/signup/_hooks/custom/use-signup-form.ts
  app/(landing)/signup/_ui/signup-complete-message/index.tsx
  app/(landing)/signup/information/page.module.scss
  app/(landing)/signup/information/page.tsx
  app/(landing)/signup/information/types.ts
  app/(landing)/signup/information/utils.ts
  app/(landing)/signup/terms-of-use/page.tsx
  app/(landing)/signup/user-type/page.tsx
  mocks/handlers/auth.ts
  shared/types/auth.ts
  shared/ui/dropdown/index.tsx
  shared/utils/validation.ts
Labels: ✨ Feature

#136 [Bug] Input 에러메시지 오류 수정
  shared/ui/error-message/error-message.stories.tsx
  shared/ui/error-message/index.tsx
  shared/ui/error-message/styles.module.scss
  shared/ui/error-messages/index.tsx
  shared/ui/input/index.tsx
Labels: 🐛 Bug

#131 [Feat] 종목&매매 아이콘 컴포넌트
  app/(dashboard)/_ui/details-information/index.tsx
  app/(dashboard)/_ui/details-information/strategy-name-box.tsx
  app/(dashboard)/_ui/strategies-item/index.tsx
  app/(dashboard)/_ui/strategies-item/strategies-icon.tsx
  app/(dashboard)/_ui/strategies-item/strategies-item.stories.tsx
  app/(dashboard)/_ui/strategies-item/strategies-summary.tsx
  app/(dashboard)/_ui/strategies-item/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/_api/get-details-information.ts
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/styles.module.scss
  mocks/handlers/strategies.ts
  mocks/handlers/strategy-details.ts
  package-lock.json
  package.json
  public/images/stock.png
  public/images/trade.png
  shared/types/strategy-details-data.ts
Labels: ✨ Feature

#130 [Feat] 트레이더 상세보기 페이지 퍼블리싱
  app/(dashboard)/traders/[traderId]/page.module.scss
  app/(dashboard)/traders/[traderId]/page.tsx
Labels: ✨ Feature, 🎨 Design

#139 [Feat] 문의내역 QuestionCard 컴포넌트 추가
  app/(dashboard)/my/questions/_ui/question-card/index.tsx
  app/(dashboard)/my/questions/_ui/question-card/question-card.stories.tsx
  app/(dashboard)/my/questions/_ui/question-card/styles.module.scss
  shared/types/questions.ts
  shared/ui/label/index.tsx
  shared/ui/label/styles.module.scss
  shared/utils/format.ts
Labels: ✨ Feature

#148 [Feat] 이용약관 페이지 및 개인정보 처리방침 페이지 퍼블리싱
  app/(landing)/privacy-terms/page.module.scss
  app/(landing)/privacy-terms/page.tsx
  app/(landing)/signup/terms-of-use/page.tsx
  app/(landing)/terms-of-use/page.module.scss
  app/(landing)/terms-of-use/page.tsx
  shared/ui/terms/investor-terms.tsx
  shared/ui/terms/privacy-terms.tsx
  shared/ui/terms/styles.module.scss
  shared/ui/terms/trader-terms.tsx
Labels: ✨ Feature

#144 [Design]: 회원가입 선택 페이지에 일러스트 추가
  app/(landing)/signup/_ui/user-type-card/index.tsx
  app/(landing)/signup/_ui/user-type-card/styles.module.scss
  app/(landing)/signup/user-type/page.module.scss
  public/images/index.ts
  public/images/investor.svg
  public/images/trader.svg
Labels: 🎨 Design

#143 [Feat] 문의내역 상세 카드 컴포넌트
  app/(dashboard)/my/questions/[questionId]/_ui/question-detail-card/index.tsx
  app/(dashboard)/my/questions/[questionId]/_ui/question-detail-card/question-detail-card.stories.tsx
  app/(dashboard)/my/questions/[questionId]/_ui/question-detail-card/styles.module.scss
  app/(dashboard)/my/questions/_ui/question-card/card-mixins.scss
  app/(dashboard)/my/questions/_ui/question-card/index.tsx
  app/(dashboard)/my/questions/_ui/question-card/styles.module.scss
Labels: ✨ Feature

#152 [Feat] 전략목록페이지 아코디언 형식의 검색 사이드바 추가
  app/(dashboard)/strategies/[strategyId]/page.tsx
  app/(dashboard)/strategies/_ui/search-bar/_hooks/use-accordion-button.ts
  app/(dashboard)/strategies/_ui/search-bar/_hooks/use-accordion-context.ts
  app/(dashboard)/strategies/_ui/search-bar/_store/use-searching-item-store.ts
  app/(dashboard)/strategies/_ui/search-bar/_type/search.ts
  app/(dashboard)/strategies/_ui/search-bar/_utils/type-validate.ts
  app/(dashboard)/strategies/_ui/search-bar/accordion-button.tsx
  app/(dashboard)/strategies/_ui/search-bar/accordion-container.tsx
  app/(dashboard)/strategies/_ui/search-bar/accordion-panel.tsx
  app/(dashboard)/strategies/_ui/search-bar/algorithm-item.tsx
  app/(dashboard)/strategies/_ui/search-bar/index.tsx
  app/(dashboard)/strategies/_ui/search-bar/range-container.tsx
  app/(dashboard)/strategies/_ui/search-bar/search-bar-tab.tsx
  app/(dashboard)/strategies/_ui/search-bar/styles.module.scss
  app/(dashboard)/strategies/_ui/side-container/index.tsx
  app/(dashboard)/strategies/_ui/side-container/styles.module.scss
  app/(dashboard)/strategies/page.tsx
Labels: ✨ Feature

#114 [Fix] table 컴포넌트의 데이터가 없는 경우 ui 추가, 훅 분리, body로 컴포넌트를 받을 수 있도록 수정
  shared/ui/table/vertical/index.tsx
  shared/ui/table/vertical/styles.module.scss
  shared/ui/table/vertical/table.stories.tsx
  shared/utils/slice-array.ts
Labels: 🔨 Refactor

#157 [Feat] 나의 전략 페이지 퍼블리싱
  app/(dashboard)/_ui/details-information/index.tsx
  app/(dashboard)/_ui/introduction/styles.module.scss
  app/(dashboard)/my/_api/get-my-strategy-list.ts
  app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
  app/(dashboard)/my/strategies/manage/[strategyId]/styles.module.scss
  app/(dashboard)/my/strategies/page.tsx
  app/(dashboard)/my/strategies/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/account-content.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/analysis-content.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/index.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/tabs-width-table.tsx
  app/(dashboard)/strategies/[strategyId]/page.tsx
  app/(dashboard)/strategies/_ui/side-container/index.tsx
  app/(dashboard)/strategies/_ui/side-container/styles.module.scss
  next.config.mjs
  shared/api/axios.ts
  shared/constants/path.ts
  shared/ui/table/vertical/index.tsx
  shared/ui/table/vertical/styles.module.scss
Labels: ✨ Feature, 🎨 Design

#161 [Refactor] 전략 API 수정 이슈로 인한 관련 로직 수정
  app/(dashboard)/_ui/details-information/index.tsx
  app/(dashboard)/_ui/strategies-item/area-chart.tsx
  app/(dashboard)/_ui/strategies-item/index.tsx
  app/(dashboard)/_ui/strategies-item/strategies-item.stories.tsx
  app/(dashboard)/my/_api/get-favorite-strategy-list.ts
  app/(dashboard)/my/_api/get-my-strategy-list.ts
  app/(dashboard)/my/_hooks/query/use-get-my-strategy-list.ts
  app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
  app/(dashboard)/strategies/[strategyId]/_api/get-details-information.ts
  app/(dashboard)/strategies/[strategyId]/_api/get-reviews.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-details-information-data.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-reviews-data.ts
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/analysis-content.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/index.tsx
  app/(dashboard)/strategies/[strategyId]/page.tsx
  app/(dashboard)/strategies/_api/get-strategies.ts
  app/(dashboard)/strategies/_ui/strategy-list/index.tsx
  mocks/handlers/strategies.ts
  mocks/handlers/strategy-details.ts
  shared/hooks/custom/use-pagination.ts
  shared/types/strategy-data.ts
  shared/ui/table/vertical/index.tsx
Labels: 🔨 Refactor

#164 [Feat] 문의내역 페이지 퍼블리싱
  app/(dashboard)/my/questions/_ui/question-card/index.tsx
  app/(dashboard)/my/questions/_ui/questions-tab-content/index.tsx
  app/(dashboard)/my/questions/_ui/questions-tab-content/styles.module.scss
  app/(dashboard)/my/questions/_ui/questions-tab/index.tsx
  app/(dashboard)/my/questions/page.module.scss
  app/(dashboard)/my/questions/page.tsx
  shared/types/questions.ts
  shared/ui/search-input/index.tsx
  shared/ui/search-input/search-input.stories.tsx
  shared/ui/search-input/styles.module.scss
Labels: ✨ Feature

#166 [Feat] 문의 내역 상세 페이지 퍼블리싱
  app/(dashboard)/my/questions/[questionId]/_ui/question-container/index.tsx
  app/(dashboard)/my/questions/[questionId]/_ui/question-container/styles.module.scss
  app/(dashboard)/my/questions/[questionId]/page.tsx
Labels: ✨ Feature

#167 [Feat] 전략상세 조건부렌더링 및 분석차트 api
  app/(dashboard)/_ui/details-side-item/index.tsx
  app/(dashboard)/_ui/details-side-item/side-item.tsx
  app/(dashboard)/_ui/strategies-item/styles.module.scss
  app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
  app/(dashboard)/strategies/[strategyId]/_api/get-analysis-chart.ts
  app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-analysis-chart.ts
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/analysis-chart.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/index.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-item.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-list.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/subscriber-item/index.tsx
  app/(dashboard)/strategies/[strategyId]/_ui/subscriber-item/styles.module.scss
  app/(dashboard)/strategies/[strategyId]/page.tsx
  next.config.mjs
Labels: ✨ Feature, 🎨 Design

#171 [Feat] 나의 전략 페이지 api 연동하여 데이터 가져오기
  app/(dashboard)/_ui/list-header/styles.module.scss
  app/(dashboard)/_ui/strategies-item/index.tsx
  app/(dashboard)/_ui/strategies-item/styles.module.scss
  app/(dashboard)/my/_api/get-my-strategy-list.ts
  app/(dashboard)/my/strategies/_ui/my-strategy-list/index.tsx
  shared/api/axios.ts
  shared/types/strategy-data.ts
Labels: ✨ Feature

#172 [Feat] 랜딩페이지 구독 상위 목록 및 sm 스코어 상위 목록 api 연결
  app/(landing)/(home)/_api/top-strategies.ts
  app/(landing)/(home)/_hooks/query/use-get-top-ranking-smscore.ts
  app/(landing)/(home)/_hooks/query/use-get-top-ranking.ts
  app/(landing)/(home)/_ui/top-favorite-section/index.tsx
  app/(landing)/(home)/_ui/top-sm-score-section/index.tsx
  next.config.mjs
  shared/types/strategy-data.ts
Labels: ✨ Feature
